//! Owns retained terminal-cell GPU shadows and exact sparse Vulkan commands.
//!
//! The package does not own Render publication or submission policy. It owns
//! one accepted instance shadow, bounded sparse candidate writes, borrowed
//! replacement input, stable blank/ASCII glyph identities, first-use atlas
//! uploads, row indirection, sparse instance transfers, and one bounded draw
//! description. Resource creation, barriers, shader/render-pass compatibility,
//! submission, and physical execution are left to future Host integration.

const std = @import("std");
const vk = @import("abi.zig");
const terminal = @import("howl_render").terminal_cells;

/// Maximum stable printable-ASCII glyph identities across four font styles.
pub const glyph_slots: usize = 95 * 4;
/// Number of stable atlas columns used by mechanical slot placement.
pub const glyph_atlas_columns: u16 = 20;
const glyph_atlas_rows: u16 = 19;
const blank_glyph: u16 = std.math.maxInt(u16);

/// Stores shader-ready resolved style flags.
pub const InstanceFlags = packed struct(u16) {
    /// Selects a bold glyph slot.
    bold: bool = false,
    /// Requests dim foreground presentation.
    dim: bool = false,
    /// Selects an italic glyph slot.
    italic: bool = false,
    /// Requests one static underline.
    underline: bool = false,
    /// Requests one static strike line.
    strikethrough: bool = false,
    /// Retains exact packed ABI space for reviewed extensions.
    reserved: u11 = 0,
};

/// Stores one persistent terminal cell consumed by the terminal pipeline.
pub const Instance = extern struct {
    /// Selects one stable glyph slot or the canonical blank sentinel.
    glyph_slot: u16,
    /// Stores shader-visible static style.
    flags: InstanceFlags,
    /// Stores packed RGBA foreground.
    foreground: u32,
    /// Stores packed RGBA background.
    background: u32,
    /// Stores packed RGBA underline color.
    underline_color: u32,
};

comptime {
    std.debug.assert(@sizeOf(Instance) == 16);
    std.debug.assert(@alignOf(Instance) == 4);
}

/// Supplies one completed raster for an exact stable glyph identity.
pub const GlyphRaster = struct {
    /// Qualifies the stable atlas slot.
    key: terminal.GlyphKey,
    /// Bounds copied mask columns.
    width: u16,
    /// Bounds copied mask rows.
    height: u16,
    /// Supplies source bytes per row.
    stride: usize,
    /// Borrows exactly `stride * height` alpha bytes.
    pixels: []const u8,
};

/// Identifies one first-use upload copied into the fixed glyph atlas.
pub const GlyphUpload = struct {
    /// Qualifies the first-use raster.
    key: terminal.GlyphKey,
    /// Identifies its stable atlas slot.
    slot: u16,
    /// Borrows the candidate-owned copied alpha bytes.
    pixels: []const u8,
    /// Supplies the exact Vulkan buffer-to-image region.
    region: vk.VkBufferImageCopy,
};

/// Describes one instanced terminal draw independent of generic Canvas Plan.
pub const Draw = struct {
    /// Uses two triangles generated by the terminal vertex pipeline.
    vertex_count: u32 = 6,
    /// Draws one instance for each active logical cell.
    instance_count: u32,
    /// Keeps the terminal pane as one bounded draw group.
    group_count: u32 = 1,
    /// Supplies static cursor state without generic-plan replay.
    cursor: terminal.Cursor,
};

/// Borrows exact candidate transfers until `Store.complete` or `Store.discard`.
pub const Prepared = struct {
    /// Supplies active logical rows.
    rows: u16,
    /// Supplies active logical columns.
    cols: u16,
    /// Names the only path that uploads every active cell, when present.
    replacement: ?terminal.ReplacementKind,
    /// Supplies exact mapped instance-staging bytes required by this candidate.
    instance_staging_bytes: usize,
    /// Borrows exact sparse staging-to-persistent buffer regions.
    instance_copies: []const vk.VkBufferCopy,
    /// Borrows a complete small row map only when indirection changes.
    row_map: []const u32,
    /// Supplies the exact row-map buffer copy when present.
    row_copy: ?vk.VkBufferCopy,
    /// Borrows copied first-use glyph staging bytes.
    glyph_pixels: []const u8,
    /// Borrows exact first-use atlas regions.
    glyph_uploads: []const GlyphUpload,
    /// Supplies one bounded terminal-pane draw.
    draw: Draw,
};

/// Borrows caller-owned persistently mapped staging partitions.
pub const MappedStaging = struct {
    /// Receives `Prepared.instance_staging_bytes` at offset zero.
    instances: []u8,
    /// Receives the byte representation of `Prepared.row_map` at offset zero.
    rows: []u8,
    /// Receives `Prepared.glyph_pixels` at offset zero.
    glyphs: []u8,
};

/// Borrows compatible Vulkan handles for sparse terminal commands.
///
/// The caller owns creation, barriers, render-pass compatibility, submission,
/// completion, and destruction. The terminal package owns only exact copies
/// and one instanced draw command over these qualified handles.
pub const CommandBindings = struct {
    /// Supplies the mapped instance staging buffer.
    instance_staging: vk.VkBuffer,
    /// Supplies persistent shader-visible terminal instances.
    instance_storage: vk.VkBuffer,
    /// Supplies the mapped row-map staging buffer.
    row_staging: vk.VkBuffer,
    /// Supplies persistent shader-visible row indirection.
    row_storage: vk.VkBuffer,
    /// Supplies mapped first-use glyph bytes.
    glyph_staging: vk.VkBuffer,
    /// Supplies the transfer-destination glyph atlas.
    glyph_atlas: vk.VkImage,
    /// Supplies the compatible terminal graphics pipeline.
    pipeline: vk.VkPipeline,
    /// Supplies its descriptor-compatible pipeline layout.
    layout: vk.VkPipelineLayout,
    /// Binds persistent instances, row map, and glyph atlas.
    descriptor: vk.VkDescriptorSet,
};

/// Fixes retained cells, rows, sparse work, and glyph staging at init.
pub const Limits = struct {
    /// Bounds persistent row indirection.
    rows: u16,
    /// Bounds persistent instances per row.
    cols: u16,
    /// Bounds individual sparse cell transfers.
    sparse_cell_updates: usize,
    /// Bounds fill and row-indirection work.
    structured_updates: usize,
    /// Bounds one stable glyph tile width.
    glyph_width: u16,
    /// Bounds one stable glyph tile height.
    glyph_height: u16,
    /// Bounds copied first-use glyph bytes per candidate.
    glyph_upload_bytes: usize,
};

/// Returns exact retained CPU bytes requested by one Store configuration.
/// Caller-mapped staging and future physical GPU allocations are borrowed or
/// unimplemented and are excluded.
pub fn retainedCpuBytes(limits: Limits) Error!usize {
    const cells = try validateLimits(limits);
    const rows: usize = limits.rows;
    const sparse = limits.sparse_cell_updates;
    const structured = limits.structured_updates;
    const glyph_words = (glyph_slots + 63) / 64;
    var total: usize = @sizeOf(Store);
    inline for (.{
        cells * @sizeOf(Instance),
        rows * @sizeOf(u32),
        rows * @sizeOf(u32),
        (sparse + structured + 1) * @sizeOf(vk.VkBufferCopy),
        sparse * @sizeOf(CellWrite),
        structured * @sizeOf(FillWrite),
        glyph_words * @sizeOf(u64),
        glyph_words * @sizeOf(u64),
        limits.glyph_upload_bytes,
        glyph_slots * @sizeOf(GlyphUpload),
    }) |bytes| total = std.math.add(usize, total, bytes) catch return error.InvalidLimits;
    return total;
}

/// Returns exact logical payload bytes future caller-owned GPU resources must
/// expose. Vulkan allocation padding and device execution remain unclaimed.
pub fn physicalPayloadBytes(limits: Limits) Error!struct {
    instances: usize,
    row_map: usize,
    glyph_atlas: usize,
} {
    const cells = try validateLimits(limits);
    const extent = try glyphAtlasExtent(limits);
    return .{
        .instances = std.math.mul(usize, cells, @sizeOf(Instance)) catch return error.InvalidLimits,
        .row_map = std.math.mul(usize, limits.rows, @sizeOf(u32)) catch return error.InvalidLimits,
        .glyph_atlas = std.math.mul(usize, extent.width, extent.height) catch return error.InvalidLimits,
    };
}

/// Reports exact retained-store construction and candidate preparation errors.
pub const Error = error{
    InvalidLimits,
    InvalidGeometry,
    InvalidIdentity,
    SparseUpdateLimit,
    StructuredUpdateLimit,
    GlyphUnavailable,
    InvalidGlyphRaster,
    GlyphUploadLimit,
    CandidatePending,
    NoCandidate,
    OutOfMemory,
};

const CellWrite = struct { index: usize, instance: Instance };
const FillWrite = struct { first: usize, count: usize, instance: Instance };

/// Retains accepted GPU shadows separately from one fixed candidate.
pub const Store = struct {
    allocator: std.mem.Allocator,
    limits: Limits,
    accepted_instances: []Instance,
    accepted_rows: []u32,
    candidate_rows: []u32,
    candidate_instance_count: usize = 0,
    buffer_copies: []vk.VkBufferCopy,
    buffer_copy_count: usize = 0,
    cell_writes: []CellWrite,
    cell_write_count: usize = 0,
    fill_writes: []FillWrite,
    fill_write_count: usize = 0,
    glyph_resident: []u64,
    candidate_glyphs: []u64,
    glyph_pixels: []u8,
    glyph_pixel_count: usize = 0,
    glyph_uploads: []GlyphUpload,
    glyph_upload_count: usize = 0,
    rows: u16 = 0,
    cols: u16 = 0,
    candidate_rows_count: u16 = 0,
    candidate_cols_count: u16 = 0,
    accepted_cursor: terminal.Cursor = .{},
    candidate_cursor: terminal.Cursor = .{},
    candidate_replacement: ?terminal.ReplacementKind = null,
    candidate_replacement_cells: []const terminal.Cell = &.{},
    candidate_row_changed: bool = false,
    candidate_pending: bool = false,

    /// Allocates all accepted and candidate storage transactionally.
    pub fn init(allocator: std.mem.Allocator, limits: Limits) Error!Store {
        const cells = try validateLimits(limits);
        const glyph_words = (glyph_slots + 63) / 64;
        const accepted_instances = allocator.alloc(Instance, cells) catch return error.OutOfMemory;
        errdefer allocator.free(accepted_instances);
        const accepted_rows = allocator.alloc(u32, limits.rows) catch return error.OutOfMemory;
        errdefer allocator.free(accepted_rows);
        const candidate_rows = allocator.alloc(u32, limits.rows) catch return error.OutOfMemory;
        errdefer allocator.free(candidate_rows);
        const buffer_copies = allocator.alloc(
            vk.VkBufferCopy,
            limits.sparse_cell_updates + limits.structured_updates + 1,
        ) catch return error.OutOfMemory;
        errdefer allocator.free(buffer_copies);
        const cell_writes = allocator.alloc(CellWrite, limits.sparse_cell_updates) catch return error.OutOfMemory;
        errdefer allocator.free(cell_writes);
        const fill_writes = allocator.alloc(FillWrite, limits.structured_updates) catch return error.OutOfMemory;
        errdefer allocator.free(fill_writes);
        const glyph_resident = allocator.alloc(u64, glyph_words) catch return error.OutOfMemory;
        errdefer allocator.free(glyph_resident);
        const candidate_glyphs = allocator.alloc(u64, glyph_words) catch return error.OutOfMemory;
        errdefer allocator.free(candidate_glyphs);
        const glyph_pixels = allocator.alloc(u8, limits.glyph_upload_bytes) catch return error.OutOfMemory;
        errdefer allocator.free(glyph_pixels);
        const glyph_uploads = allocator.alloc(GlyphUpload, glyph_slots) catch return error.OutOfMemory;
        errdefer allocator.free(glyph_uploads);
        @memset(accepted_instances, blankInstance());
        @memset(accepted_rows, 0);
        @memset(candidate_rows, 0);
        @memset(glyph_resident, 0);
        @memset(candidate_glyphs, 0);
        return .{
            .allocator = allocator,
            .limits = limits,
            .accepted_instances = accepted_instances,
            .accepted_rows = accepted_rows,
            .candidate_rows = candidate_rows,
            .buffer_copies = buffer_copies,
            .cell_writes = cell_writes,
            .fill_writes = fill_writes,
            .glyph_resident = glyph_resident,
            .candidate_glyphs = candidate_glyphs,
            .glyph_pixels = glyph_pixels,
            .glyph_uploads = glyph_uploads,
        };
    }

    /// Releases every fixed allocation in reverse construction order.
    pub fn deinit(self: *Store) void {
        self.allocator.free(self.glyph_uploads);
        self.allocator.free(self.glyph_pixels);
        self.allocator.free(self.candidate_glyphs);
        self.allocator.free(self.glyph_resident);
        self.allocator.free(self.fill_writes);
        self.allocator.free(self.cell_writes);
        self.allocator.free(self.buffer_copies);
        self.allocator.free(self.candidate_rows);
        self.allocator.free(self.accepted_rows);
        self.allocator.free(self.accepted_instances);
        self.* = undefined;
    }

    /// Prepares one Render-owned terminal update without changing accepted GPU
    /// shadows or generic Canvas/Vulkan Plan storage.
    pub fn prepare(
        self: *Store,
        update: terminal.Update,
        rasters: []const GlyphRaster,
    ) Error!Prepared {
        if (self.candidate_pending) return error.CandidatePending;
        self.resetCandidate();
        errdefer self.resetCandidate();
        const cells = try validateUpdate(self.limits, update);
        if (update.replacement) |replacement| switch (replacement.kind) {
            .initialization => if (self.rows != 0) return error.InvalidIdentity,
            .resize, .alternate_grid => if (self.rows == 0) return error.InvalidIdentity,
        };
        self.candidate_rows_count = update.rows;
        self.candidate_cols_count = update.cols;
        self.candidate_cursor = update.cursor orelse self.accepted_cursor;
        try self.stageGlyphs(update.glyphs, rasters);

        if (update.replacement) |replacement| {
            self.candidate_replacement = replacement.kind;
            self.candidate_replacement_cells = replacement.cells;
            for (replacement.cells) |cell| try self.requireInstance(cell);
            self.candidate_instance_count = cells;
            try self.appendCopy(0, 0, cells);
            for (self.candidate_rows[0..update.rows], 0..) |*row, index|
                row.* = @intCast(index);
            self.candidate_row_changed = true;
        } else {
            if (self.rows != update.rows or self.cols != update.cols)
                return error.InvalidGeometry;
            @memcpy(self.candidate_rows[0..self.rows], self.accepted_rows[0..self.rows]);
            for (update.row_rotations) |rotation| {
                try applyRotation(self.candidate_rows[0..self.rows], rotation);
                self.candidate_row_changed = true;
            }
            for (update.fills) |fill_update| try self.stageFill(fill_update);
            for (update.cells) |cell_update| try self.stageCell(cell_update);
        }

        self.candidate_pending = true;
        return self.prepared();
    }

    fn prepared(self: *const Store) Prepared {
        std.debug.assert(self.candidate_pending);
        return .{
            .rows = self.candidate_rows_count,
            .cols = self.candidate_cols_count,
            .replacement = self.candidate_replacement,
            .instance_staging_bytes = self.candidate_instance_count * @sizeOf(Instance),
            .instance_copies = self.buffer_copies[0..self.buffer_copy_count],
            .row_map = if (self.candidate_row_changed)
                self.candidate_rows[0..self.candidate_rows_count]
            else
                &.{},
            .row_copy = if (self.candidate_row_changed) .{
                .srcOffset = 0,
                .dstOffset = 0,
                .size = @as(u64, self.candidate_rows_count) * @sizeOf(u32),
            } else null,
            .glyph_pixels = self.glyph_pixels[0..self.glyph_pixel_count],
            .glyph_uploads = self.glyph_uploads[0..self.glyph_upload_count],
            .draw = .{
                .instance_count = @intCast(
                    @as(usize, self.candidate_rows_count) * self.candidate_cols_count,
                ),
                .cursor = self.candidate_cursor,
            },
        };
    }

    /// Accepts one prepared sparse candidate after its physical GPU work has
    /// completed successfully. This operation is infallible and allocation-free.
    pub fn complete(self: *Store) Error!void {
        if (!self.candidate_pending) return error.NoCandidate;
        if (self.candidate_replacement != null) {
            const cells: usize = @as(usize, self.candidate_rows_count) * self.candidate_cols_count;
            for (self.candidate_replacement_cells[0..cells], 0..) |cell, index|
                self.accepted_instances[index] = self.instanceFor(cell) catch unreachable;
        } else {
            for (self.fill_writes[0..self.fill_write_count]) |fill_write|
                @memset(
                    self.accepted_instances[fill_write.first .. fill_write.first + fill_write.count],
                    fill_write.instance,
                );
            for (self.cell_writes[0..self.cell_write_count]) |cell_write|
                self.accepted_instances[cell_write.index] = cell_write.instance;
        }
        if (self.candidate_row_changed)
            @memcpy(
                self.accepted_rows[0..self.candidate_rows_count],
                self.candidate_rows[0..self.candidate_rows_count],
            );
        for (self.candidate_glyphs, 0..) |word, index|
            self.glyph_resident[index] |= word;
        self.rows = self.candidate_rows_count;
        self.cols = self.candidate_cols_count;
        self.accepted_cursor = self.candidate_cursor;
        self.candidate_pending = false;
        self.resetCandidate();
    }

    /// Discards candidate ownership without changing any accepted shadow.
    pub fn discard(self: *Store) Error!void {
        if (!self.candidate_pending) return error.NoCandidate;
        self.candidate_pending = false;
        self.resetCandidate();
    }

    /// Returns one accepted physical instance for deterministic owner proofs.
    pub fn accepted(self: *const Store, physical_index: usize) Error!Instance {
        const count = @as(usize, self.rows) * self.cols;
        if (physical_index >= count) return error.InvalidGeometry;
        return self.accepted_instances[physical_index];
    }

    /// Reports whether one exact printable-ASCII/style raster is resident.
    pub fn glyphResident(self: *const Store, key: terminal.GlyphKey) bool {
        const slot = glyphSlot(key) catch return false;
        return bit(self.glyph_resident, slot);
    }

    /// Copies the internally owned candidate into caller-mapped staging only
    /// after every partition and candidate fact passes preflight.
    pub fn stageMapped(self: *const Store, staging: MappedStaging) Error!void {
        try self.validateCandidate();
        const candidate = self.prepared();
        const row_bytes = std.mem.sliceAsBytes(candidate.row_map);
        if (candidate.instance_staging_bytes > staging.instances.len)
            return error.SparseUpdateLimit;
        if (row_bytes.len > staging.rows.len) return error.StructuredUpdateLimit;
        if (candidate.glyph_pixels.len > staging.glyphs.len) return error.GlyphUploadLimit;

        var byte_offset: usize = 0;
        if (self.candidate_replacement != null) {
            for (self.candidate_replacement_cells) |cell| {
                const instance = try self.instanceFor(cell);
                const bytes = std.mem.asBytes(&instance);
                @memcpy(staging.instances[byte_offset..][0..bytes.len], bytes);
                byte_offset += bytes.len;
            }
        } else {
            for (self.fill_writes[0..self.fill_write_count]) |fill_write| {
                const bytes = std.mem.asBytes(&fill_write.instance);
                for (0..fill_write.count) |_| {
                    @memcpy(staging.instances[byte_offset..][0..bytes.len], bytes);
                    byte_offset += bytes.len;
                }
            }
            for (self.cell_writes[0..self.cell_write_count]) |cell_write| {
                const bytes = std.mem.asBytes(&cell_write.instance);
                @memcpy(staging.instances[byte_offset..][0..bytes.len], bytes);
                byte_offset += bytes.len;
            }
        }
        std.debug.assert(byte_offset == candidate.instance_staging_bytes);
        @memcpy(staging.rows[0..row_bytes.len], row_bytes);
        @memcpy(staging.glyphs[0..candidate.glyph_pixels.len], candidate.glyph_pixels);
    }

    /// Records exact candidate transfers after complete validation. Failure
    /// occurs before the first Vulkan command.
    pub fn recordTransfers(
        self: *const Store,
        command: vk.VkCommandBuffer,
        bindings: CommandBindings,
    ) Error!void {
        try validateCommandBindings(command, bindings);
        try self.validateCandidate();
        const candidate = self.prepared();
        const instance_copy_count = std.math.cast(u32, candidate.instance_copies.len) orelse
            return error.InvalidGeometry;
        const glyph_upload_count = std.math.cast(u32, candidate.glyph_uploads.len) orelse
            return error.InvalidGeometry;
        var regions: [glyph_slots]vk.VkBufferImageCopy = undefined;
        for (candidate.glyph_uploads, 0..) |upload, index| regions[index] = upload.region;

        if (instance_copy_count != 0)
            vk.vkCmdCopyBuffer(
                command,
                bindings.instance_staging,
                bindings.instance_storage,
                instance_copy_count,
                candidate.instance_copies.ptr,
            );
        if (candidate.row_copy) |row_copy|
            vk.vkCmdCopyBuffer(command, bindings.row_staging, bindings.row_storage, 1, &row_copy);
        if (glyph_upload_count != 0)
            vk.vkCmdCopyBufferToImage(
                command,
                bindings.glyph_staging,
                bindings.glyph_atlas,
                vk.VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
                glyph_upload_count,
                &regions,
            );
    }

    /// Records one bounded terminal draw after candidate and count validation.
    /// Resource creation, barriers, render-pass compatibility, submission, and
    /// physical execution remain caller-owned and unimplemented here.
    pub fn recordDraw(
        self: *const Store,
        command: vk.VkCommandBuffer,
        bindings: CommandBindings,
    ) Error!void {
        try validateCommandBindings(command, bindings);
        try self.validateCandidate();
        const candidate = self.prepared();
        vk.vkCmdBindPipeline(command, vk.VK_PIPELINE_BIND_POINT_GRAPHICS, bindings.pipeline);
        vk.vkCmdBindDescriptorSets(
            command,
            vk.VK_PIPELINE_BIND_POINT_GRAPHICS,
            bindings.layout,
            0,
            1,
            &bindings.descriptor,
            0,
            null,
        );
        vk.vkCmdDraw(command, candidate.draw.vertex_count, candidate.draw.instance_count, 0, 0);
    }

    fn validateCandidate(self: *const Store) Error!void {
        if (!self.candidate_pending) return error.NoCandidate;
        const cells = std.math.mul(
            usize,
            self.candidate_rows_count,
            self.candidate_cols_count,
        ) catch return error.InvalidGeometry;
        const persistent_cells = std.math.mul(usize, self.limits.rows, self.limits.cols) catch
            return error.InvalidGeometry;
        if (cells == 0 or cells > persistent_cells) return error.InvalidGeometry;
        const staging_bytes = std.math.mul(usize, self.candidate_instance_count, @sizeOf(Instance)) catch
            return error.InvalidGeometry;
        const persistent_bytes = std.math.mul(usize, persistent_cells, @sizeOf(Instance)) catch
            return error.InvalidGeometry;
        if (self.buffer_copy_count > self.buffer_copies.len or
            self.glyph_upload_count > glyph_slots or
            self.glyph_upload_count > self.glyph_uploads.len)
            return error.InvalidGeometry;

        var covered_bytes: usize = 0;
        for (self.buffer_copies[0..self.buffer_copy_count]) |copy| {
            if (copy.size == 0 or copy.srcOffset % @alignOf(Instance) != 0 or
                copy.dstOffset % @alignOf(Instance) != 0 or
                copy.size % @sizeOf(Instance) != 0)
                return error.InvalidGeometry;
            const source_end = std.math.add(u64, copy.srcOffset, copy.size) catch
                return error.InvalidGeometry;
            const destination_end = std.math.add(u64, copy.dstOffset, copy.size) catch
                return error.InvalidGeometry;
            if (copy.srcOffset != covered_bytes or source_end > staging_bytes or
                destination_end > persistent_bytes)
                return error.InvalidGeometry;
            covered_bytes = std.math.add(usize, covered_bytes, @intCast(copy.size)) catch
                return error.InvalidGeometry;
        }
        if (covered_bytes != staging_bytes) return error.InvalidGeometry;

        if (self.candidate_replacement != null) {
            if (self.candidate_replacement_cells.len != cells or
                self.candidate_instance_count != cells or self.buffer_copy_count != 1)
                return error.InvalidGeometry;
            for (self.candidate_replacement_cells) |cell| try self.requireInstance(cell);
        } else {
            var staged: usize = self.cell_write_count;
            for (self.fill_writes[0..self.fill_write_count]) |fill_write|
                staged = std.math.add(usize, staged, fill_write.count) catch
                    return error.InvalidGeometry;
            if (staged != self.candidate_instance_count or
                self.buffer_copy_count != self.fill_write_count + self.cell_write_count or
                staged > self.limits.sparse_cell_updates)
                return error.InvalidGeometry;
        }

        const row_bytes = std.math.mul(usize, self.candidate_rows_count, @sizeOf(u32)) catch
            return error.InvalidGeometry;
        if (self.candidate_row_changed) {
            if (self.candidate_rows_count > self.candidate_rows.len) return error.InvalidGeometry;
            var seen_rows: [1024]u64 = @splat(0);
            for (self.candidate_rows[0..self.candidate_rows_count]) |row| {
                if (row >= self.candidate_rows_count or bit(&seen_rows, row))
                    return error.InvalidGeometry;
                setBit(&seen_rows, row);
            }
            const copy = self.prepared().row_copy orelse return error.InvalidGeometry;
            if (copy.srcOffset != 0 or copy.dstOffset != 0 or copy.size != row_bytes)
                return error.InvalidGeometry;
        } else if (self.prepared().row_copy != null) return error.InvalidGeometry;

        if (self.glyph_pixel_count > self.glyph_pixels.len) return error.InvalidGeometry;
        var seen: [(glyph_slots + 63) / 64]u64 = @splat(0);
        for (self.glyph_uploads[0..self.glyph_upload_count]) |upload| {
            const slot: usize = upload.slot;
            if (slot >= glyph_slots or bit(&seen, slot) or
                upload.slot != glyphSlot(upload.key) catch return error.InvalidIdentity)
                return error.InvalidGeometry;
            setBit(&seen, slot);
            const region = upload.region;
            if (region.bufferOffset % 4 != 0 or region.bufferRowLength == 0 or
                region.bufferImageHeight == 0 or region.imageExtent.width == 0 or
                region.imageExtent.height == 0 or region.imageExtent.depth != 1 or
                region.imageSubresource.aspectMask != vk.VK_IMAGE_ASPECT_COLOR_BIT or
                region.imageSubresource.mipLevel != 0 or
                region.imageSubresource.baseArrayLayer != 0 or
                region.imageSubresource.layerCount != 1)
                return error.InvalidGlyphRaster;
            const bytes = std.math.mul(u64, region.bufferRowLength, region.bufferImageHeight) catch
                return error.InvalidGlyphRaster;
            const end = std.math.add(u64, region.bufferOffset, bytes) catch
                return error.InvalidGlyphRaster;
            const expected_x = @as(i32, @intCast(slot % glyph_atlas_columns)) * self.limits.glyph_width;
            const expected_y = @as(i32, @intCast(slot / glyph_atlas_columns)) * self.limits.glyph_height;
            if (end > self.glyph_pixel_count or upload.pixels.len != bytes or
                upload.pixels.ptr != self.glyph_pixels.ptr + region.bufferOffset or
                region.imageOffset.x != expected_x or region.imageOffset.y != expected_y or
                region.imageOffset.z != 0 or
                region.imageExtent.width > self.limits.glyph_width or
                region.imageExtent.height > self.limits.glyph_height or
                region.bufferRowLength < region.imageExtent.width or
                region.bufferImageHeight < region.imageExtent.height)
                return error.InvalidGlyphRaster;
        }
        const draw_count = std.math.cast(u32, cells) orelse return error.InvalidGeometry;
        const draw = self.prepared().draw;
        if (draw.vertex_count != 6 or draw.group_count != 1 or draw.instance_count != draw_count)
            return error.InvalidGeometry;
    }

    fn stageGlyphs(
        self: *Store,
        keys: []const terminal.GlyphKey,
        rasters: []const GlyphRaster,
    ) Error!void {
        for (keys) |key| {
            const slot = try glyphSlot(key);
            if (bit(self.glyph_resident, slot) or bit(self.candidate_glyphs, slot)) continue;
            const raster = findRaster(rasters, key) orelse return error.GlyphUnavailable;
            try self.stageGlyph(slot, raster);
        }
    }

    fn stageGlyph(self: *Store, slot: usize, raster: GlyphRaster) Error!void {
        if (raster.width == 0 or raster.height == 0 or
            raster.width > self.limits.glyph_width or
            raster.height > self.limits.glyph_height or
            raster.stride < raster.width)
            return error.InvalidGlyphRaster;
        const bytes = std.math.mul(usize, raster.stride, raster.height) catch
            return error.InvalidGlyphRaster;
        if (raster.pixels.len != bytes) return error.InvalidGlyphRaster;
        const offset = std.mem.alignForward(usize, self.glyph_pixel_count, 4);
        const next = std.math.add(usize, offset, bytes) catch
            return error.GlyphUploadLimit;
        if (next > self.glyph_pixels.len or self.glyph_upload_count == self.glyph_uploads.len)
            return error.GlyphUploadLimit;
        @memset(self.glyph_pixels[self.glyph_pixel_count..offset], 0);
        @memcpy(self.glyph_pixels[offset..next], raster.pixels);
        const column: u16 = @intCast(slot % glyph_atlas_columns);
        const row: u16 = @intCast(slot / glyph_atlas_columns);
        self.glyph_uploads[self.glyph_upload_count] = .{
            .key = raster.key,
            .slot = @intCast(slot),
            .pixels = self.glyph_pixels[offset..next],
            .region = .{
                .bufferOffset = offset,
                .bufferRowLength = @intCast(raster.stride),
                .bufferImageHeight = raster.height,
                .imageSubresource = .{
                    .aspectMask = vk.VK_IMAGE_ASPECT_COLOR_BIT,
                    .mipLevel = 0,
                    .baseArrayLayer = 0,
                    .layerCount = 1,
                },
                .imageOffset = .{
                    .x = @as(i32, column) * self.limits.glyph_width,
                    .y = @as(i32, row) * self.limits.glyph_height,
                    .z = 0,
                },
                .imageExtent = .{
                    .width = raster.width,
                    .height = raster.height,
                    .depth = 1,
                },
            },
        };
        self.glyph_upload_count += 1;
        self.glyph_pixel_count = next;
        setBit(self.candidate_glyphs, slot);
    }

    fn stageFill(self: *Store, update: terminal.FillUpdate) Error!void {
        if (self.fill_write_count == self.fill_writes.len)
            return error.StructuredUpdateLimit;
        const first: usize = @intCast(update.first);
        const count: usize = @intCast(update.count);
        const maximum: usize = @as(usize, self.rows) * self.cols;
        if (count == 0 or first > maximum or count > maximum - first)
            return error.InvalidGeometry;
        const instance = try self.instanceFor(update.cell);
        if (count > self.limits.sparse_cell_updates -| self.candidate_instance_count)
            return error.SparseUpdateLimit;
        const transfer_first = self.candidate_instance_count;
        self.candidate_instance_count += count;
        try self.appendCopy(transfer_first, first, count);
        self.fill_writes[self.fill_write_count] = .{
            .first = first,
            .count = count,
            .instance = instance,
        };
        self.fill_write_count += 1;
    }

    fn stageCell(self: *Store, update: terminal.CellUpdate) Error!void {
        if (self.cell_write_count == self.cell_writes.len)
            return error.SparseUpdateLimit;
        const index: usize = @intCast(update.physical_index);
        const maximum: usize = @as(usize, self.rows) * self.cols;
        if (index >= maximum) return error.InvalidGeometry;
        if (self.candidate_instance_count == self.limits.sparse_cell_updates)
            return error.SparseUpdateLimit;
        const instance = try self.instanceFor(update.cell);
        const transfer_index = self.candidate_instance_count;
        self.candidate_instance_count += 1;
        try self.appendCopy(transfer_index, index, 1);
        self.cell_writes[self.cell_write_count] = .{ .index = index, .instance = instance };
        self.cell_write_count += 1;
    }

    fn appendCopy(self: *Store, source: usize, destination: usize, count: usize) Error!void {
        if (self.buffer_copy_count == self.buffer_copies.len)
            return error.StructuredUpdateLimit;
        self.buffer_copies[self.buffer_copy_count] = .{
            .srcOffset = @as(u64, source) * @sizeOf(Instance),
            .dstOffset = @as(u64, destination) * @sizeOf(Instance),
            .size = @as(u64, count) * @sizeOf(Instance),
        };
        self.buffer_copy_count += 1;
    }

    fn instanceFor(self: *const Store, cell: terminal.Cell) Error!Instance {
        const slot = if (cell.codepoint == 0 or cell.codepoint == ' ')
            blank_glyph
        else blk: {
            const key = terminal.GlyphKey{
                .codepoint = @intCast(cell.codepoint),
                .bold = cell.style.bold,
                .italic = cell.style.italic,
            };
            const value = try glyphSlot(key);
            if (!bit(self.glyph_resident, value) and !bit(self.candidate_glyphs, value))
                return error.GlyphUnavailable;
            break :blk @as(u16, @intCast(value));
        };
        return .{
            .glyph_slot = slot,
            .flags = .{
                .bold = cell.style.bold,
                .dim = cell.style.dim,
                .italic = cell.style.italic,
                .underline = cell.style.underline,
                .strikethrough = cell.style.strikethrough,
            },
            .foreground = color(cell.foreground),
            .background = color(cell.background),
            .underline_color = color(cell.underline_color),
        };
    }

    fn requireInstance(self: *const Store, cell: terminal.Cell) Error!void {
        const instance = try self.instanceFor(cell);
        if (instance.flags.reserved != 0) return error.InvalidIdentity;
    }

    fn resetCandidate(self: *Store) void {
        self.candidate_instance_count = 0;
        self.buffer_copy_count = 0;
        self.cell_write_count = 0;
        self.fill_write_count = 0;
        self.glyph_pixel_count = 0;
        self.glyph_upload_count = 0;
        @memset(self.candidate_glyphs, 0);
        self.candidate_replacement = null;
        self.candidate_replacement_cells = &.{};
        self.candidate_row_changed = false;
        self.candidate_rows_count = 0;
        self.candidate_cols_count = 0;
    }
};

/// Returns the fixed atlas extent required by one Store configuration.
pub fn glyphAtlasExtent(limits: Limits) Error!struct { width: u32, height: u32 } {
    const retained_cells = try validateLimits(limits);
    std.debug.assert(retained_cells > 0);
    return .{
        .width = @as(u32, limits.glyph_width) * glyph_atlas_columns,
        .height = @as(u32, limits.glyph_height) * glyph_atlas_rows,
    };
}

fn validateLimits(limits: Limits) Error!usize {
    if (limits.rows == 0 or limits.cols == 0 or
        limits.sparse_cell_updates == 0 or limits.structured_updates == 0 or
        limits.glyph_width == 0 or limits.glyph_height == 0 or
        limits.glyph_upload_bytes == 0 or
        limits.sparse_cell_updates > terminal.maximum_cells or
        limits.structured_updates > terminal.maximum_cells)
        return error.InvalidLimits;
    const cells = std.math.mul(usize, limits.rows, limits.cols) catch
        return error.InvalidLimits;
    const atlas_width = std.math.mul(u32, limits.glyph_width, glyph_atlas_columns) catch
        return error.InvalidLimits;
    const atlas_height = std.math.mul(u32, limits.glyph_height, glyph_atlas_rows) catch
        return error.InvalidLimits;
    if (atlas_width == 0 or atlas_height == 0 or cells > terminal.maximum_cells)
        return error.InvalidLimits;
    const copy_capacity = std.math.add(
        usize,
        limits.sparse_cell_updates,
        limits.structured_updates,
    ) catch return error.InvalidLimits;
    if (copy_capacity < limits.sparse_cell_updates) return error.InvalidLimits;
    return cells;
}

fn validateCommandBindings(
    command: vk.VkCommandBuffer,
    bindings: CommandBindings,
) Error!void {
    if (command == null or bindings.instance_staging == null or
        bindings.instance_storage == null or bindings.row_staging == null or
        bindings.row_storage == null or bindings.glyph_staging == null or
        bindings.glyph_atlas == null or bindings.pipeline == null or
        bindings.layout == null or bindings.descriptor == null)
        return error.InvalidIdentity;
}

fn validateUpdate(limits: Limits, update: terminal.Update) Error!usize {
    if (update.rows == 0 or update.cols == 0 or
        update.rows > limits.rows or update.cols > limits.cols)
        return error.InvalidGeometry;
    const cells = std.math.mul(usize, update.rows, update.cols) catch
        return error.InvalidGeometry;
    if (update.replacement) |replacement| {
        if (replacement.rows != update.rows or replacement.cols != update.cols or
            replacement.cells.len != cells or update.row_rotations.len != 0 or
            update.fills.len != 0 or update.cells.len != 0)
            return error.InvalidGeometry;
    }
    if (update.row_rotations.len > limits.structured_updates or
        update.fills.len > limits.structured_updates)
        return error.StructuredUpdateLimit;
    if (update.cells.len > limits.sparse_cell_updates)
        return error.SparseUpdateLimit;
    if (update.cursor) |cursor| {
        if (cursor.visible and (cursor.shape == .hidden or
            cursor.row >= update.rows or cursor.col >= update.cols))
            return error.InvalidGeometry;
        if (!cursor.visible and !std.meta.eql(cursor, terminal.Cursor{}))
            return error.InvalidIdentity;
    }
    return cells;
}

fn glyphSlot(key: terminal.GlyphKey) Error!usize {
    if (key.reserved != 0 or key.codepoint < 0x20 or key.codepoint > 0x7e)
        return error.InvalidIdentity;
    const style: usize = @as(usize, @intFromBool(key.bold)) |
        (@as(usize, @intFromBool(key.italic)) << 1);
    return (@as(usize, key.codepoint) - 0x20) * 4 + style;
}

fn findRaster(rasters: []const GlyphRaster, key: terminal.GlyphKey) ?GlyphRaster {
    for (rasters) |raster| if (raster.key == key) return raster;
    return null;
}

fn applyRotation(rows: []u32, rotation: terminal.RowRotation) Error!void {
    if (rotation.count == 0 or rotation.first >= rows.len or
        @as(usize, rotation.count) > rows.len - rotation.first or
        rotation.shift == 0 or @abs(rotation.shift) >= rotation.count)
        return error.InvalidGeometry;
    const region = rows[rotation.first .. rotation.first + rotation.count];
    if (rotation.shift < 0) {
        std.mem.rotate(u32, region, @intCast(-rotation.shift));
    } else {
        std.mem.rotate(u32, region, region.len - @as(usize, @intCast(rotation.shift)));
    }
}

fn blankInstance() Instance {
    return .{
        .glyph_slot = blank_glyph,
        .flags = .{},
        .foreground = 0,
        .background = 0,
        .underline_color = 0,
    };
}

fn color(value: terminal.Rgb) u32 {
    return @as(u32, value.r) |
        (@as(u32, value.g) << 8) |
        (@as(u32, value.b) << 16) |
        (@as(u32, 0xff) << 24);
}

fn bit(words: []const u64, index: usize) bool {
    return words[index / 64] & (@as(u64, 1) << @intCast(index % 64)) != 0;
}

fn setBit(words: []u64, index: usize) void {
    words[index / 64] |= @as(u64, 1) << @intCast(index % 64);
}

fn testCell(codepoint: u21) terminal.Cell {
    return terminal.Cell.init(
        codepoint,
        .{ .r = 0xee, .g = 0xee, .b = 0xee },
        .{ .r = 0x11, .g = 0x11, .b = 0x11 },
        .{ .r = 0x88, .g = 0x88, .b = 0x88 },
        .{},
    );
}

fn testLimits(rows: u16, cols: u16) Limits {
    return .{
        .rows = rows,
        .cols = cols,
        .sparse_cell_updates = @as(usize, rows) * cols,
        .structured_updates = rows,
        .glyph_width = 8,
        .glyph_height = 16,
        .glyph_upload_bytes = 4096,
    };
}

fn testRaster(key: terminal.GlyphKey, pixels: []const u8) GlyphRaster {
    return .{ .key = key, .width = 1, .height = 1, .stride = 1, .pixels = pixels };
}

fn testCommandBindings() CommandBindings {
    return .{
        .instance_staging = @ptrFromInt(1),
        .instance_storage = @ptrFromInt(1),
        .row_staging = @ptrFromInt(1),
        .row_storage = @ptrFromInt(1),
        .glyph_staging = @ptrFromInt(1),
        .glyph_atlas = @ptrFromInt(1),
        .pipeline = @ptrFromInt(1),
        .layout = @ptrFromInt(1),
        .descriptor = @ptrFromInt(1),
    };
}

fn acceptInitial(grid: *terminal.Grid, store: *Store, pixels: []const u8) !void {
    const update = (try grid.prepare()).?;
    var rasters: [glyph_slots]GlyphRaster = undefined;
    var raster_count: usize = 0;
    for (update.glyphs) |key| {
        rasters[raster_count] = testRaster(key, pixels);
        raster_count += 1;
    }
    const prepared = try store.prepare(update, rasters[0..raster_count]);
    try std.testing.expectEqual(terminal.ReplacementKind.initialization, prepared.replacement.?);
    try store.complete();
    try grid.complete();
}

fn storeAllocationFailure(allocator: std.mem.Allocator) !void {
    var store = try Store.init(allocator, testLimits(2, 2));
    defer store.deinit();
}

test "render grid lowers through retained Vulkan storage without Plan copies" {
    var grid = try terminal.Grid.init(
        std.testing.allocator,
        .{ .rows = 4, .cols = 5, .structured_operations = 8, .sparse_cell_updates = 20 },
        4,
        5,
        testCell('5'),
    );
    defer grid.deinit();
    var store = try Store.init(std.testing.allocator, testLimits(4, 5));
    defer store.deinit();
    const pixels = [_]u8{0xff};
    try acceptInitial(&grid, &store, &pixels);

    try grid.set(1, 2, testCell('4'));
    try grid.set(1, 2, testCell('5'));
    try std.testing.expect((try grid.prepare()) == null);

    try grid.set(1, 2, testCell('4'));
    const update = (try grid.prepare()).?;
    const key = update.glyphs[0];
    const prepared = try store.prepare(update, &.{testRaster(key, &pixels)});
    try std.testing.expectEqual(@as(usize, @sizeOf(Instance)), prepared.instance_staging_bytes);
    try std.testing.expectEqual(@as(usize, 1), prepared.instance_copies.len);
    try std.testing.expectEqual(@as(u64, 0), prepared.instance_copies[0].srcOffset);
    try std.testing.expectEqual(@as(u64, 7 * @sizeOf(Instance)), prepared.instance_copies[0].dstOffset);
    try std.testing.expectEqual(@as(u64, @sizeOf(Instance)), prepared.instance_copies[0].size);
    try std.testing.expectEqual(@as(u32, 1), prepared.draw.group_count);
    try std.testing.expectEqual(@as(u32, 20), prepared.draw.instance_count);
    try store.complete();
    try grid.complete();
}

test "maximum-cell retained CPU and future payload equations are exact" {
    const limits = Limits{
        .rows = 128,
        .cols = 512,
        .sparse_cell_updates = terminal.maximum_cells,
        .structured_updates = terminal.maximum_cells,
        .glyph_width = 8,
        .glyph_height = 16,
        .glyph_upload_bytes = terminal.maximum_cells,
    };
    const physical = try physicalPayloadBytes(limits);
    try std.testing.expectEqual(@as(usize, 312), @sizeOf(Store));
    try std.testing.expectEqual(@as(usize, 7_961_712), try retainedCpuBytes(limits));
    try std.testing.expectEqual(@as(usize, 1_048_576), physical.instances);
    try std.testing.expectEqual(@as(usize, 512), physical.row_map);
    try std.testing.expectEqual(@as(usize, 48_640), physical.glyph_atlas);
}

test "GPU replacement lifecycle rejects premature and duplicate initialization" {
    var grid = try terminal.Grid.init(
        std.testing.allocator,
        .{ .rows = 1, .cols = 1, .structured_operations = 1, .sparse_cell_updates = 1 },
        1,
        1,
        testCell(' '),
    );
    defer grid.deinit();
    var store = try Store.init(std.testing.allocator, testLimits(1, 1));
    defer store.deinit();
    const initial = (try grid.prepare()).?;
    var premature = initial;
    var premature_replacement = premature.replacement.?;
    premature_replacement.kind = .resize;
    premature.replacement = premature_replacement;
    try std.testing.expectError(error.InvalidIdentity, store.prepare(premature, &.{}));

    const prepared = try store.prepare(initial, &.{});
    try std.testing.expectEqual(terminal.ReplacementKind.initialization, prepared.replacement.?);
    try store.complete();
    try grid.complete();
    const before = try store.accepted(0);
    try std.testing.expectError(error.InvalidIdentity, store.prepare(initial, &.{}));
    try std.testing.expectEqualDeep(before, try store.accepted(0));
}

test "one-row scroll uploads row map and exposed row but no moved cells" {
    var grid = try terminal.Grid.init(
        std.testing.allocator,
        .{ .rows = 4, .cols = 5, .structured_operations = 8, .sparse_cell_updates = 5 },
        4,
        5,
        testCell('a'),
    );
    defer grid.deinit();
    var store = try Store.init(std.testing.allocator, testLimits(4, 5));
    defer store.deinit();
    const pixels = [_]u8{0xff};
    try acceptInitial(&grid, &store, &pixels);
    try grid.copyRows(1, 0, 3);
    try grid.fill(3, 0, 1, 5, testCell(' '));
    const update = (try grid.prepare()).?;
    const prepared = try store.prepare(update, &.{});
    try std.testing.expect(prepared.row_copy != null);
    try std.testing.expectEqualSlices(u32, &.{ 1, 2, 3, 0 }, prepared.row_map);
    try std.testing.expectEqual(@as(u64, 4 * @sizeOf(u32)), prepared.row_copy.?.size);
    try std.testing.expectEqual(@as(usize, 5 * @sizeOf(Instance)), prepared.instance_staging_bytes);
    try std.testing.expectEqual(@as(usize, 1), prepared.instance_copies.len);
    try std.testing.expectEqual(@as(u64, 0), prepared.instance_copies[0].dstOffset);
    try std.testing.expectEqual(@as(u64, 5 * @sizeOf(Instance)), prepared.instance_copies[0].size);
    try store.complete();
    try grid.complete();
}

test "stable glyph identity uploads only on first use" {
    var grid = try terminal.Grid.init(
        std.testing.allocator,
        .{ .rows = 1, .cols = 2, .structured_operations = 2, .sparse_cell_updates = 2 },
        1,
        2,
        testCell(' '),
    );
    defer grid.deinit();
    var store = try Store.init(std.testing.allocator, testLimits(1, 2));
    defer store.deinit();
    try acceptInitial(&grid, &store, &.{});
    const pixels = [_]u8{0xaa};
    try grid.set(0, 0, testCell('x'));
    const first = (try grid.prepare()).?;
    const key = first.glyphs[0];
    const first_prepared = try store.prepare(first, &.{testRaster(key, &pixels)});
    try std.testing.expectEqual(@as(usize, 1), first_prepared.glyph_uploads.len);
    try std.testing.expectEqual(
        @as(u16, @intCast(try glyphSlot(key))),
        first_prepared.glyph_uploads[0].slot,
    );
    try store.complete();
    try grid.complete();
    try std.testing.expect(store.glyphResident(key));

    try grid.set(0, 1, testCell('x'));
    const second = (try grid.prepare()).?;
    const second_prepared = try store.prepare(second, &.{});
    try std.testing.expectEqual(@as(usize, 0), second_prepared.glyph_uploads.len);
    try store.complete();
    try grid.complete();
}

test "mapped staging preflights all partitions before writing" {
    var grid = try terminal.Grid.init(
        std.testing.allocator,
        .{ .rows = 1, .cols = 1, .structured_operations = 1, .sparse_cell_updates = 1 },
        1,
        1,
        testCell(' '),
    );
    defer grid.deinit();
    var store = try Store.init(std.testing.allocator, testLimits(1, 1));
    defer store.deinit();
    try acceptInitial(&grid, &store, &.{});
    const accepted_before = try store.accepted(0);

    const pixels = [_]u8{0x7f};
    try grid.set(0, 0, testCell('x'));
    const update = (try grid.prepare()).?;
    const prepared = try store.prepare(update, &.{testRaster(update.glyphs[0], &pixels)});
    var instance_bytes: [@sizeOf(Instance)]u8 = undefined;
    var glyph_bytes: [1]u8 = undefined;
    try store.stageMapped(.{
        .instances = &instance_bytes,
        .rows = &.{},
        .glyphs = &glyph_bytes,
    });
    try std.testing.expectEqual(@as(usize, @sizeOf(Instance)), prepared.instance_staging_bytes);
    try std.testing.expectEqualSlices(u8, prepared.glyph_pixels, &glyph_bytes);

    var short_instances: [@sizeOf(Instance) - 1]u8 = @splat(0xaa);
    var untouched_rows: [3]u8 = @splat(0xbb);
    var untouched_glyphs: [1]u8 = @splat(0xcc);
    try std.testing.expectError(error.SparseUpdateLimit, store.stageMapped(.{
        .instances = &short_instances,
        .rows = &untouched_rows,
        .glyphs = &untouched_glyphs,
    }));
    for (short_instances) |byte| try std.testing.expectEqual(@as(u8, 0xaa), byte);
    for (untouched_rows) |byte| try std.testing.expectEqual(@as(u8, 0xbb), byte);
    for (untouched_glyphs) |byte| try std.testing.expectEqual(@as(u8, 0xcc), byte);

    var glyph_instances: [@sizeOf(Instance)]u8 = @splat(0x44);
    var glyph_rows: [0]u8 = .{};
    var no_glyph_space: [0]u8 = .{};
    try std.testing.expectError(error.GlyphUploadLimit, store.stageMapped(.{
        .instances = &glyph_instances,
        .rows = &glyph_rows,
        .glyphs = &no_glyph_space,
    }));
    for (glyph_instances) |byte| try std.testing.expectEqual(@as(u8, 0x44), byte);
    try std.testing.expectEqualDeep(accepted_before, try store.accepted(0));
    try store.discard();
    try grid.discard();
}

test "first-use glyph copy offsets satisfy Vulkan alignment" {
    var grid = try terminal.Grid.init(
        std.testing.allocator,
        .{ .rows = 1, .cols = 2, .structured_operations = 1, .sparse_cell_updates = 2 },
        1,
        2,
        testCell(' '),
    );
    defer grid.deinit();
    var limits = testLimits(1, 2);
    limits.glyph_upload_bytes = 5;
    var store = try Store.init(std.testing.allocator, limits);
    defer store.deinit();
    try acceptInitial(&grid, &store, &.{});

    const first_pixels = [_]u8{0x11};
    const second_pixels = [_]u8{0x22};
    try grid.set(0, 0, testCell('x'));
    try grid.set(0, 1, testCell('y'));
    const update = (try grid.prepare()).?;
    const prepared = try store.prepare(update, &.{
        testRaster(update.glyphs[0], &first_pixels),
        testRaster(update.glyphs[1], &second_pixels),
    });
    try std.testing.expectEqual(@as(usize, 2), prepared.glyph_uploads.len);
    try std.testing.expectEqual(@as(u64, 0), prepared.glyph_uploads[0].region.bufferOffset);
    try std.testing.expectEqual(@as(u64, 4), prepared.glyph_uploads[1].region.bufferOffset);
    try std.testing.expectEqualSlices(u8, &.{ 0x11, 0, 0, 0, 0x22 }, prepared.glyph_pixels);
    try store.discard();
    try grid.discard();
}

test "cursor update draws without generic base geometry copy" {
    var grid = try terminal.Grid.init(
        std.testing.allocator,
        .{ .rows = 2, .cols = 2, .structured_operations = 2, .sparse_cell_updates = 1 },
        2,
        2,
        testCell(' '),
    );
    defer grid.deinit();
    var store = try Store.init(std.testing.allocator, testLimits(2, 2));
    defer store.deinit();
    try acceptInitial(&grid, &store, &.{});
    try grid.setCursor(.{ .row = 1, .col = 1, .shape = .block, .visible = true });
    const update = (try grid.prepare()).?;
    const prepared = try store.prepare(update, &.{});
    try std.testing.expectEqual(@as(usize, 0), prepared.instance_staging_bytes);
    try std.testing.expectEqual(@as(usize, 0), prepared.instance_copies.len);
    try std.testing.expect(prepared.draw.cursor.visible);
    try store.complete();
    try grid.complete();
}

test "glyph and sparse preparation failures preserve accepted ownership" {
    var grid = try terminal.Grid.init(
        std.testing.allocator,
        .{ .rows = 1, .cols = 2, .structured_operations = 2, .sparse_cell_updates = 2 },
        1,
        2,
        testCell(' '),
    );
    defer grid.deinit();
    var store = try Store.init(std.testing.allocator, .{
        .rows = 1,
        .cols = 2,
        .sparse_cell_updates = 1,
        .structured_updates = 1,
        .glyph_width = 1,
        .glyph_height = 1,
        .glyph_upload_bytes = 1,
    });
    defer store.deinit();
    try acceptInitial(&grid, &store, &.{});
    const before = try store.accepted(0);
    try grid.set(0, 0, testCell('x'));
    const update = (try grid.prepare()).?;
    try std.testing.expectError(error.GlyphUnavailable, store.prepare(update, &.{}));
    try std.testing.expectEqualDeep(before, try store.accepted(0));
    const bad_pixels = [_]u8{ 1, 2 };
    try std.testing.expectError(
        error.InvalidGlyphRaster,
        store.prepare(update, &.{.{
            .key = update.glyphs[0],
            .width = 1,
            .height = 1,
            .stride = 1,
            .pixels = &bad_pixels,
        }}),
    );
    try std.testing.expectEqualDeep(before, try store.accepted(0));

    var invalid_geometry = update;
    invalid_geometry.cursor = .{ .row = 1, .col = 0, .shape = .block, .visible = true };
    try std.testing.expectError(error.InvalidGeometry, store.prepare(invalid_geometry, &.{}));
    try std.testing.expectEqualDeep(before, try store.accepted(0));
    const invalid_keys = [_]terminal.GlyphKey{.{
        .codepoint = 1,
        .bold = false,
        .italic = false,
    }};
    var invalid_identity = update;
    invalid_identity.glyphs = &invalid_keys;
    try std.testing.expectError(error.InvalidIdentity, store.prepare(invalid_identity, &.{}));
    try std.testing.expectEqualDeep(before, try store.accepted(0));

    try grid.discard();
    try grid.set(0, 1, testCell('x'));
    const overflow_update = (try grid.prepare()).?;
    const pixels = [_]u8{0xaa};
    try std.testing.expectError(
        error.SparseUpdateLimit,
        store.prepare(overflow_update, &.{testRaster(overflow_update.glyphs[0], &pixels)}),
    );
    try std.testing.expectEqualDeep(before, try store.accepted(0));
    try grid.discard();
}

test "allocation and Vulkan command layouts are exact" {
    try std.testing.checkAllAllocationFailures(
        std.testing.allocator,
        storeAllocationFailure,
        .{},
    );
    try std.testing.expectEqual(@as(usize, 24), @sizeOf(vk.VkBufferCopy));
    try std.testing.expectEqual(@as(usize, 56), @sizeOf(vk.VkBufferImageCopy));
    const copy_command: *const fn (
        vk.VkCommandBuffer,
        vk.VkBuffer,
        vk.VkBuffer,
        u32,
        [*c]const vk.VkBufferCopy,
    ) callconv(.c) void = &vk.vkCmdCopyBuffer;
    const draw_command: *const fn (
        vk.VkCommandBuffer,
        u32,
        u32,
        u32,
        u32,
    ) callconv(.c) void = &vk.vkCmdDraw;
    try std.testing.expect(@intFromPtr(copy_command) != 0);
    try std.testing.expect(@intFromPtr(draw_command) != 0);
    const transfer_owner: *const fn (
        *const Store,
        vk.VkCommandBuffer,
        CommandBindings,
    ) Error!void = &Store.recordTransfers;
    const draw_owner: *const fn (
        *const Store,
        vk.VkCommandBuffer,
        CommandBindings,
    ) Error!void = &Store.recordDraw;
    try std.testing.expect(@intFromPtr(transfer_owner) != 0);
    try std.testing.expect(@intFromPtr(draw_owner) != 0);
    const invalid = std.mem.zeroes(CommandBindings);
    var store = try Store.init(std.testing.allocator, testLimits(1, 1));
    defer store.deinit();
    try std.testing.expectError(error.InvalidIdentity, store.recordTransfers(null, invalid));
    try std.testing.expectError(error.InvalidIdentity, store.recordDraw(null, invalid));
    const extent = try glyphAtlasExtent(testLimits(2, 2));
    try std.testing.expectEqual(@as(u32, 160), extent.width);
    try std.testing.expectEqual(@as(u32, 304), extent.height);
}

test "malformed retained commands fail before the first Vulkan call" {
    var grid = try terminal.Grid.init(
        std.testing.allocator,
        .{ .rows = 1, .cols = 1, .structured_operations = 1, .sparse_cell_updates = 1 },
        1,
        1,
        testCell(' '),
    );
    defer grid.deinit();
    var store = try Store.init(std.testing.allocator, testLimits(1, 1));
    defer store.deinit();
    const update = (try grid.prepare()).?;
    const candidate = try store.prepare(update, &.{});
    try std.testing.expectEqual(terminal.ReplacementKind.initialization, candidate.replacement.?);

    const command: vk.VkCommandBuffer = @ptrFromInt(1);
    const bindings = testCommandBindings();
    store.buffer_copies[0].srcOffset = 1;
    try std.testing.expectError(error.InvalidGeometry, store.recordTransfers(command, bindings));
    store.buffer_copies[0].srcOffset = 0;

    store.candidate_rows[0] = 1;
    try std.testing.expectError(error.InvalidGeometry, store.recordTransfers(command, bindings));
    store.candidate_rows[0] = 0;

    store.glyph_upload_count = glyph_slots + 1;
    try std.testing.expectError(error.InvalidGeometry, store.recordTransfers(command, bindings));
    store.glyph_upload_count = 0;

    store.candidate_instance_count = 0;
    try std.testing.expectError(error.InvalidGeometry, store.recordDraw(command, bindings));
}
