# Repository-local configuration.
font.path /usr/share/fonts/TTF/IosevkaTermNerdFont-Regular.ttf
cursor.shape beam
cursor.color #73f990
cursor.unfocused_shape hollow
cursor.beam_thickness_points 1.5
cursor.underline_thickness_points 2.0
