name: howl_flutter
description: Flutter platform host for the native Howl client.
publish_to: none
version: 0.1.6-dev+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.4

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
